# NumPy
Doc: https://numpy.org/doc/stable/

In [2]:
#from numpy import *
import numpy as np

In [3]:
L1 = [1,2,3,4,5,6,7,8] # Lista

In [4]:
x1 = np.array(L1)   #Transforma la lista en array de np
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
x2 = np.array(L1, dtype='float')    #declara el tipo de variable
x2

array([1., 2., 3., 4., 5., 6., 7., 8.])

## Tipos de Datos
- bool_
- int_, intc, intp, int8, int16, int32, int64
- float_, float16, float32, float64
- complex_, complex64, complex128 

In [6]:
np.zeros( (3,4) )   #Genera una matriz de ceros con 3 filas y 4 columnas

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones( (4,3) )    #Genera una matriz de unos con 4 filas y 3 columnas

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.arange(10)   # Crea un arreglo de n numeros desde 0 a n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3, 12, dtype=np.float_)  # Crea un arreglo desde 3 hasta 11 de tipo float

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [13]:
np.arange(4, 5, 0.1)    # Crea un arreglo entre 4 y 5 sumando 0.1

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])